export const geolocationErrorTypes = {
  NO_GEOLOCATION_SUPPORT: 'NO_GEOLOCATION_SUPPORT',
  TIMEOUT_EXPIRED: 3,
  TIMEOUT_LOCATION_DATA: 'TIMEOUT_LOCATION_DATA',
  USER_DENIED_GEOLOCATION: 1,
  USER_IS_OFFLINE: 2,
}
